name: soif
description: For soil moisture monitoring.

version: 2.0.0+alpha

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^2.1.1+1
  syncfusion_flutter_charts: ^1.0.0-beta.4
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.4.1
  flutter_image: ^3.0.0
  provider: ^4.0.2
  shared_preferences: ^0.5.6
  package_info: ^0.4.0+13

  cupertino_icons: ^0.1.3
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/Soif_sk.png
   - assets/images/Soif_sk_dark.png
   - assets/images/plant.png
   - assets/images/plant_dark.png

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Bold-Italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-ExtraBold-Italic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Medium-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Regular.ttf